apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  labels:
    app: myfirstwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstwebsite
  template:
    metadata:
      labels:
        app: myfirstwebsite
    spec:
      containers:
      - name: myfirstwebsite
        image: devlopmentacr.azurecr.io/myfirstwebsite:3c6c04f89db66e4111b13b65d50ee890280f5e1b
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: myfirstwebsite
  ports:
    - protocol: TCP
     # port: 80
      #targetPort: 80
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mywebsite-ingress 
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mywebsite.com
    http:
      paths:
      - backend:
          service:
            name: mywebsite-service
            port:
              number: 80
        path: /
        pathType: Prefix
