apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  labels:
    app: myfirstwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstwebsite
  template:
    metadata:
      labels:
        app: myfirstwebsite
    spec:
      containers:
      - name: myfirstwebsite
        image: devlopmentacr.azurecr.io/myfirstwebsite:3c6c04f89db66e4111b13b65d50ee890280f5e1b
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: myfirstwebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
