apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  labels:
    app: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: devlopmentacr.azurecr.io/dotnetapp:v1
        ports:
        - containerPort: 80