on: [push]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master

         - uses: Azure/docker-login@v1
           with:
              login-server: devlopmentacr.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build . -t devlopmentacr.azurecr.io/mywebsite:${{ github.sha }}
              docker push devlopmentacr.azurecr.io/mywebsite:${{ github.sha }}

         - uses: azure/setup-kubectl@v2.0

         # Set the target AKS cluster.
         - uses: Azure/aks-set-context@v1
           with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              cluster-name: learnk8scluster
              resource-group: learnk8sResourceGroup

         - uses: Azure/k8s-create-secret@v1.1
           with:
              container-registry-url: devlopmentacr.azurecr.io
              container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
              container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              secret-name: demo-k8s-secret

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              manifests: |
                 manifests/Azure-deploy.yml
              images: |
               devlopmentacr.azurecr.io/mywebsite:${{ github.sha }}
               imagepullsecrets: |
                 demo-k8s-secret